version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  nestjs:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      MONGO_URI: mongodb://mongodb:27017/nest
      REDIS_HOST: redis
      REDIS_PORT: 6379
